# -*- coding: utf-8 -*-
"""GP_MIU_Tables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12xU0ejaXGNjT_2Eo53R6gKQKFv-l1-jX

Add these two load functions at the top of app.py where the other load functions are:
"""

@st.cache_data
def load_gp():
    try:
        return pd.read_csv(
            'https://raw.githubusercontent.com/125109486-dev/Health-Flow-Datasets-Code/refs/heads/main/gp_out_of_hours.csv',
            encoding='latin-1'
        )
    except:
        return pd.DataFrame()

@st.cache_data
def load_miu():
    try:
        return pd.read_csv(
            'https://raw.githubusercontent.com/125109486-dev/Health-Flow-Datasets-Code/refs/heads/main/minor_injury_units.csv',
            encoding='latin-1'
        )
    except:
        return pd.DataFrame()

gp_df  = load_gp()
miu_df = load_miu()

"""Then find the Resources tab in app.py and add this where the GP and MIU sections are:"""

#Get selected county
selected_county = st.session_state.get('user_county', None)

if selected_county:
    st.markdown(f"""
    <div style="background:#CCFBF1;border:1px solid #0D9488;border-radius:8px;
                padding:10px 16px;margin-bottom:1rem;font-size:13px;color:#0D2137;">
      Showing services for <strong>{selected_county}</strong>
    </div>
    """, unsafe_allow_html=True)
else:
    selected_county = st.selectbox(
        "Select your county to see local services",
        [""] + sorted([
            'Carlow','Cavan','Clare','Cork','Donegal','Dublin','Galway',
            'Kerry','Kildare','Kilkenny','Laois','Leitrim','Limerick',
            'Longford','Louth','Mayo','Meath','Monaghan','Offaly',
            'Roscommon','Sligo','Tipperary','Waterford','Westmeath',
            'Wexford','Wicklow'
        ]),
        key="resources_county"
    )
    if selected_county:
        st.session_state.user_county = selected_county

#GP Out of Hours
st.markdown('<div class="sec-title">GP Out-of-Hours Services</div>',
            unsafe_allow_html=True)

if not gp_df.empty and selected_county:
    county_gp = gp_df[gp_df['county'].str.lower() == selected_county.lower()]
    if len(county_gp) > 0:
        for _, row in county_gp.iterrows():
            st.markdown(f"""
            <div class="res-card" style="margin-bottom:10px;">
              <div style="font-size:14px;font-weight:600;color:#0D2137;margin-bottom:4px;">
                {row['name']}
              </div>
              <div style="font-size:12px;color:#64748B;margin-bottom:6px;">
                {row['address']}
              </div>
              <div style="font-size:12px;color:#374151;">
                {row['hours']} &nbsp;·&nbsp; {row['days']}
              </div>
            </div>
            """, unsafe_allow_html=True)
    else:
        st.markdown(f"""
        <div style="background:#FEF9C3;border:1px solid #FDE68A;border-radius:8px;
                    padding:14px;font-size:13px;color:#374151;">
          No GP out-of-hours service found for <strong>{selected_county}</strong>.
          Call <strong>1850 24 1850</strong> (HSE Live) for your nearest service.
        </div>
        """, unsafe_allow_html=True)
else:
    st.info("Select your county above to see local GP out-of-hours services.")

# ── Minor Injury Units ────────────────────────────────────────
st.markdown('<div class="sec-title">Minor Injury Units</div>',
            unsafe_allow_html=True)

if not miu_df.empty and selected_county:
    county_miu = miu_df[miu_df['county'].str.lower() == selected_county.lower()]
    if len(county_miu) > 0:
        cols = st.columns(min(len(county_miu), 2))
        for i, (_, row) in enumerate(county_miu.iterrows()):
            with cols[i % 2]:
                st.markdown(f"""
                <div class="res-card" style="margin-bottom:10px;">
                  <div style="font-size:14px;font-weight:600;color:#0D2137;
                              margin-bottom:4px;">{row['name']}</div>
                  <div style="font-size:12px;color:#64748B;margin-bottom:6px;">
                    {row['address']}
                  </div>
                  <div style="font-size:12px;color:#374151;margin-bottom:3px;">
                    {row['hours']}
                  </div>
                  <div style="font-size:12px;color:#374151;margin-bottom:3px;">
                    {row['days']}
                  </div>
                  <div style="font-size:12px;color:#374151;">
                    Ages: {row['ages']}
                  </div>
                </div>
                """, unsafe_allow_html=True)
    else:
        st.markdown(f"""
        <div style="background:#FEF9C3;border:1px solid #FDE68A;border-radius:8px;
                    padding:14px;font-size:13px;color:#374151;">
          No Minor Injury Unit in <strong>{selected_county}</strong>.
          See <a href="https://www.hse.ie/eng/services/list/3/injuryunits/"
          target="_blank" style="color:#0D9488;">HSE Injury Units</a>
          for the full national list.
        </div>
        """, unsafe_allow_html=True)
else:
    st.info("Select your county above to see local Minor Injury Units.")

"""The county gets saved to st.session_state.user_county when the user completes the insurance onboarding form.
Make sure wherever Step 3 of the insurance form is confirmed, it includes:
"""

st.session_state.user_county = selected_county